version: '3.8'

services:
  # AI Reviewer Service
  ai-reviewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab-ai-reviewer
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-reviewer-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: ai-reviewer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ai-reviewer-network
    command: redis-server --appendonly yes

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: ai-reviewer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ai-reviewer
    restart: unless-stopped
    networks:
      - ai-reviewer-network

volumes:
  redis_data:
    driver: local

networks:
  ai-reviewer-network:
    driver: bridge
